DROP DATABASE bdcrespo;

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE DATABASE IF NOT EXISTS `bdcrespo` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `bdcrespo`;

DROP TABLE IF EXISTS `Imoveis`;
CREATE TABLE IF NOT EXISTS `Imoveis` (
  `IMO_COD` int(11) NOT NULL AUTO_INCREMENT,
  `IMO_NOME` varchar(100) CHARACTER SET utf8 NOT NULL,
  `IMO_TIPO` varchar(30) CHARACTER SET utf8 NOT NULL,
  `IMO_CATEGORIA` varchar(30) CHARACTER SET utf8 NOT NULL,
  `IMO_BAIRRO` varchar(200) CHARACTER SET utf8 NOT NULL,
  `IMO_SUITES` int(11) NOT NULL,
  `IMO_QUARTOS` int(11) NOT NULL,
  `IMO_AREA_TOTAL` float NOT NULL,
  `IMO_AREA_CONSTRUIDA` float NOT NULL,
  `IMO_REFORMAS` int(11) NOT NULL,
  `IMO_VAGAS` int(11) NOT NULL,
  `IMO_BANHEIROS` int(11) NOT NULL,
  `IMO_CONDOMINIO` tinyint(1) NOT NULL,
  `IMO_ENDERECO_CONDOMINIO` text CHARACTER SET utf8,
  `IMO_CARACTERISTICAS` text CHARACTER SET utf8 NOT NULL,
  `IMO_DESCRICAO` text,
  `IMO_PRECO_VENDA` decimal(9,2) NOT NULL,
  `IMO_PRECO_ALUGUEL` decimal(9,2) NOT NULL,
  `IMO_DESTAQUE` tinyint(1) NOT NULL DEFAULT '0',
  `IMO_ATIVO` tinyint(1) NOT NULL DEFAULT '1',
  `IMO_FOTOS` text CHARACTER SET utf8 NOT NULL,
  `IMO_SITUACAO` int(1) NOT NULL DEFAULT '1' COMMENT '1 - Vigente, 2 - Em negociação, 3 - Alugado, 4 - Vendido',
  PRIMARY KEY (`IMO_COD`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=latin1;

INSERT INTO `Imoveis` (`IMO_COD`, `IMO_NOME`, `IMO_TIPO`, `IMO_CATEGORIA`, `IMO_BAIRRO`, `IMO_SUITES`, `IMO_QUARTOS`, `IMO_AREA_TOTAL`, `IMO_AREA_CONSTRUIDA`, `IMO_REFORMAS`, `IMO_VAGAS`, `IMO_BANHEIROS`, `IMO_CONDOMINIO`, `IMO_ENDERECO_CONDOMINIO`, `IMO_CARACTERISTICAS`, `IMO_DESCRICAO`, `IMO_PRECO_VENDA`, `IMO_PRECO_ALUGUEL`, `IMO_DESTAQUE`, `IMO_ATIVO`, `IMO_FOTOS`, `IMO_SITUACAO`) VALUES
(13, 'Teste', 'Casa', 'Comprar', 'bairro', 2, 2, 100, 80, 2, 2, 1, 0, '', 'a:10:{i:1;s:16:\"Caracteristica 1\";i:6;s:16:\"Caracteristica 6\";i:2;s:16:\"Caracteristica 2\";i:7;s:16:\"Caracteristica 7\";i:3;s:16:\"Caracteristica 3\";i:8;s:16:\"Caracteristica 8\";i:4;s:16:\"Caracteristica 4\";i:9;s:16:\"Caracteristica 9\";i:5;s:16:\"Caracteristica 5\";i:10;s:17:\"Caracteristica 10\";}', 'DescriÃƒÂ§ÃƒÂ£o ', '30.00', '20.00', 1, 1, 'a:1:{s:5:\"foto0\";s:15:\"1542823253.jpeg\";}', 1);

DROP TABLE IF EXISTS `Usuario`;
CREATE TABLE IF NOT EXISTS `Usuario` (
  `USU_COD` int(11) NOT NULL AUTO_INCREMENT,
  `USU_LOGIN` varchar(200) NOT NULL,
  `USU_SENHA` text NOT NULL,
  PRIMARY KEY (`USU_COD`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

INSERT INTO `Usuario` (`USU_COD`, `USU_LOGIN`, `USU_SENHA`) VALUES
(2, 'UserTest', '$2a$10$r94J6TqcLoEll7ikaEJKj.p9p1JO.G6wEmsbtavM9qWQzvkOga/kK');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
